### ISSUE TITLE
Request: windows app version, 16x16 and 32x32 support

### ISSUE THREAD

**Issue by ghost** [Quinten/random-tileset-generator#2]
Hey, I have these free-for-all assets:
https://imgur.com/a/MQIjVV9

I'd love if there was a windows app version of this generator where I could just throw the png files into correct folders (tiles, toppings, plants) and the program would automatically load them all and just have a single button to randomize all and spit out a new randomized tilemap.

The assets are in 16x16px and 32px tile format, but the generator currently only supports 8x8. I'd prefer the higher detail of the former two, as 8x8 is too minimal for me.

**Comment by Quinten** [comment]
You can run this on your local machine if you fork or clone it and then do the commands in the 'Messing with the code' section in the readme. Should work on windows too with node.js installed.

Looking at your assets (which look great btw), i think it might need a whole different implementation of the generator. I also see no 'corner' tiles in your assets or other ways the patterns connect together. Is that correct?

**Comment by ghost** [comment]
Yeah unfortunately the assets I posted are just that and nothing else. No corner or walls.

I downloaded the source, then went inside the assets folder and discovered this generator works more manually than I first thought; it actually has each tile as a complete set, whereas I thought it was using code to automatically apply shadow to create the wall and corner pieces. 

I thought it did things more modular-like, where the user simply tosses their single seperate texture images into a folder, be it a tile, plant or background, then the app would just data-drivenly grab the assets from those folders and generates tilemaps out of them.

I was mistaken.
